interface Colors {
  [key: string]: string;
}

interface ThemeColors {
  [key: string]: string;
}

const COLORS: Colors = {
  BLACK: '#000000',
  BLACK_LIGHTER: '#949494',
  DEFAULT: '#81c440',
  GRAY_CLOUD: '#c5c6d0',
  GRAY_SHADOW: '#373737',
  GRAY_FLINT: '#787276',
  GRAY_ORIGINAL: '#808080',
  RED_LIGHTEST: '#ffa07a',
  RED_LIGHTER: '#fa8072',
  RED_ORIGINAL: '#ff0000',
  RED_DARKER: '#ca4343',
  RED_DARKEST: '#b22222',
  RADIANT_GREEN_DARKEST: '#4d7526',
  RADIANT_GREEN_DARKER: '#679c33',
  RADIANT_GREEN_ORIGINAL: '#81c440',
  RADIANT_GREEN_LIGHTER: '#9acf66',
  RADIANT_GREEN_LIGHTEST: '#b3db8c',
  TRANSPARENT: 'transparent',
  WHITE: '#FFFFFF',
  GRAY_BORDER: '#818181',
  GRAYISH_GREEN: '#2A392C',
  ORANGE: '#faad15',
  INFO_BLUE: '#1890ff',
  ERROR_RED: '#ff4d4f',
  DARK_BLUE: '#1e3a8a',
  DARK_GREEN: '#14532d',
};

const THEME_COLORS: ThemeColors = {
  DARKEST: COLORS.RADIANT_GREEN_DARKEST,
  DARKER: COLORS.RADIANT_GREEN_DARKER,
  ORIGINAL: COLORS.RADIANT_GREEN_ORIGINAL,
  LIGHTER: COLORS.RADIANT_GREEN_LIGHTER,
  LIGHTEST: COLORS.RADIANT_GREEN_LIGHTEST,
  TEXT_DEFAULT: COLORS.BLACK,
  TEXT_WHITE: COLORS.WHITE,
  BG_DEFAULT: COLORS.WHITE,
  GRAY: COLORS.GRAY_FLINT,
  GRAYISH_GREEN: COLORS.GRAYISH_GREEN,
  RED: COLORS.RED_DARKEST,
  INFO: COLORS.INFO_BLUE,
  WARN: COLORS.ORANGE,
  SUCCESS: COLORS.RADIANT_GREEN_ORIGINAL,
  ERROR: COLORS.ERROR_RED,
  DARKBLUE: COLORS.DARK_BLUE,
  DARKGREEN: COLORS.DARK_GREEN,
  BORDERS: COLORS.BLACK_LIGHTER,
};

export {
  COLORS,
  THEME_COLORS,
};